[package]
name = "nst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.clap]
version = "4.0.29"
features = ["derive"]

[dependencies.prost]
version = "0.11.3"
features = ["prost-derive"]

[dependencies.prost-build]
version = "0.11.4"

[dependencies.tokio]
version = "1.0.0"
features = ["full"]

[dependencies.tendermint-rpc]
version = "0.28.0"
features = ["http-client"]

[dependencies]
cosmos = {path = "../packages/cosmos"}
nova = {path = "../packages/nova"}
futures = "0.3.25"