[package]
name = "nova"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.prost]
version = "0.11.3"
features = ["prost-derive"]

[dependencies.prost-types]
version = "0.11.2"

[dependencies.cosmrs]
version = "0.11.0"

[dependencies.tendermint-rpc]
version = "0.28.0"
features = ["http-client"]

[dependencies]
clap = "4.0.29"
cosmos = {path = "../cosmos"}
ibc-proto = "0.24.0"
chrono = "0.4.23"